# Generated by Django 5.1.5 on 2025-01-24 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0003_expensecategory_user_incomesource_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='incomesource',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='incomesource',
            unique_together={('name', 'user')},
        ),
    ]
