# Generated by Django 5.1.5 on 2026-02-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0005_expense_currency_income_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='color_theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('pink', 'Pink'), ('lightBlue', 'Light Blue'), ('brown', 'Brown'), ('grey', 'Grey'), ('green', 'Green')], default='blue', max_length=10),
        ),
    ]
