# Generated by Django 5.1.5 on 2026-02-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_tracker', '0006_userprofile_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('PLN', 'Polish Złoty'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='USD', max_length=3),
        ),
    ]
